#define observable_nu_countryA_vac1 y[0]
#define observable_nu_countryB_vac1 y[1]
#define observable_proportion_countryA_vac1 y[2]
#define observable_proportion_countryB_vac1 y[3]
#define observable_time y[4]