#define dJy0_dobservable_nu_countryA_vac1 dJydy[0]
#define dJy0_dobservable_nu_countryB_vac1_1 dJydy[1]
#define dJy0_dobservable_proportion_countryA_vac1_2 dJydy[2]
#define dJy0_dobservable_proportion_countryB_vac1_3 dJydy[3]
#define dJy0_dobservable_time_4 dJydy[4]