name: Vacc

channels:
  - defaults
  - opensourceeconomics
  - conda-forge
  - bioconda

dependencies:
  - python=3.8
  - respy
  - pandas
  - numpy
  - seaborn
  - jupyterlab
  - jupyter
  - pip
  - pytest-flake8
  - libsbml
  - estimagic
  
  - pip:
    - black
    - pdbpp
    - blackcellmagic
    - pytest-black
